<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="CV.xsl"?>
<!DOCTYPE cv[
<!ELEMENT cv (me*,education*,employment*,hobandint*)>
<!ELEMENT me (name,address,telephone,email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT education (qualification*)>
<!ELEMENT qualification (organization,type,from,to)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT employment (experience*)>
<!ELEMENT experience (organization,job_title,from,to)>
<!ELEMENT job_title (#PCDATA)>
<!ELEMENT hobandint (ul*)>
<!ELEMENT ul (li+)>
<!ELEMENT li (#PCDATA)>
]>

<cv>
	<me >
		<name>Sushil Sharma</name>
		<address>Himalayan Valley, Nepal</address>
		<telephone>+977-9841-234567</telephone>
		<email>sushilsharma@duck.com</email>
	</me>
	<education>
		<qualification >
			<organization>University of Wollongong Dubai</organization>
			<type>Bachelor of Computer Science</type>
			<from>2018</from>
			<to>2023</to>
		</qualification>
		<qualification>
			<organization>CBSE Board</organization>
			<type>Higher Secondary Education</type>
			<from>2005</from>
			<to>2017</to>
		</qualification>
	</education>
	<employment>
		<experience>
			<organization>UOWD Student Representative Council</organization>
			<job_title>General Member</job_title>
			<from >2019</from>
			<to>2021</to>
		</experience>
		<experience>
			<organization>Freelance Web Development</organization>
			<job_title>Full Stack Developer</job_title>
			<from>2019</from>
			<to>Present</to>			
		</experience>
		<experience>
			<organization>Tech Startup Inc.</organization>
			<job_title>Junior Software Engineer</job_title>
			<from>2022</from>
			<to>Present</to>			
		</experience>
	</employment>
	<hobandint>
		<ul>
			<li>VideoGraphy</li>
			<li>Programming</li>
			<li>Cybersecurity</li>
			<li>Technical Writing</li>
			<li>Photography</li>
			<li>Mountain Trekking</li>
		</ul>
	</hobandint>
</cv>
